### ISSUE TITLE
ICOM IC-2730 issue

### ISSUE THREAD

**Issue by pierluigipisanti** [bbathe/civkeyer#1]
Hi I got this error:

2020/10/22 21:15:12 window.go:120: yaml: line 20: did not find expected key

I have copied your yaml.file and when start program I got this error. Where I wrong ?
Thanks
Peter

**Comment by bbathe** [comment]
I just pushed a build (https://github.com/bbathe/civkeyer/releases/tag/v0.14) that has all the latest changes (I had forgot to do a build after some cleanup work).  There is also a yaml file included in the release, you'll have to download both the civkeyer.exe.zip & civkeyer.yaml.zip and unzip them into the same folder.

It will also log a line after it reads & parses the yaml file so if this doesn't fix your issue, hopefully we get more information.

**Comment by pierluigipisanti** [comment]
thanks. now start. I have changed latest line with this :

label: F4 READ
    message: FEFE90E0030000FD
    expectreply: true

based on this CV-I information for IC-2730...but app not responding. I have cnhanged on COM3 and setup on radio 9600 baud rate.

![immagine](https://user-images.githubusercontent.com/6120011/96924432-ee51bb00-14b2-11eb-920a-aaad946a0054.png)


![immagine](https://user-images.githubusercontent.com/6120011/96924083-6ec3ec00-14b2-11eb-916c-8da26ce1a800.png)

No log file created...app freezed and do nothing. 

Suggestion ?
Thanks

**Comment by bbathe** [comment]
Going against my ic-7300, this is the command to read the frequency: FEFE94E003FD.  So, leave out sub command and BCD code data...if I included zeros the radio send back an error.

The other problem is that I didn't really intend this to read data from the radio, only to send commands to the radio that would make it do something...change the frequency or play the recorded Voice TX messages.

I do have a bug right now that will prevent that for radios that have a address other than 0x94.  I'll get that changed here shortly.

Thanks

**Comment by bbathe** [comment]
I am pushing the fix now for the hardcoded radio address (https://github.com/bbathe/civkeyer/releases/tag/v0.15).  I tested setting the frequency of the radio using this message: FEFE94E0050010100700FD and it works.  If you change the radio address from 94 to 90, it should work on the IC-2730.

This is a really great site for learning about the CI-V commands: http://www.plicht.de/ekki/civ/

**Comment by pierluigipisanti** [comment]
great ! work fine. just latest question about "read display". I got this error  : 
2020/10/23 07:12:52 civkeyer.go:104: error response from radio FEFE90E003FD FEFEE090035062554201FD
2020/10/23 07:12:52 window.go:32: error response from radio
so...seems that read frequency but got alway error -> 142.556250 is frequency on display.

**Comment by bbathe** [comment]
Yah, that's because this app doesn't handle any other responses than OK/Not Good.

![image](https://user-images.githubusercontent.com/1015871/96992046-51fdd780-14f7-11eb-974d-003fc6641186.png)

I don't have anywhere to display the data returned from the radio, I'm just checking that the last command sent was processed OK.

Here's an example that just reads the frequency, you'd have to work thru formatting the returned data:

```golang
package main

import (
	"bytes"
	"encoding/hex"
	"log"
	"time"

	"github.com/tarm/serial"
)

func main() {
	c := &serial.Config{
		Name:        "COM9",
		Baud:        9600,
		ReadTimeout: time.Second * 10,
	}

	port, err := serial.OpenPort(c)
	if err != nil {
		log.Printf("%+v", err)
		return
	}
	defer port.Close()

	// write message bytes to port
	msg, err := hex.DecodeString("FEFE94E003FD")
	if err != nil {
		log.Printf("%+v", err)
		return
	}
	_, err = port.Write(msg)
	if err != nil {
		log.Printf("%+v", err)
		return
	}

	// read response
	var buf bytes.Buffer
	b := []byte{0}

	for {
		n, err := port.Read(b)
		if err != nil {
			log.Printf("%+v", err)
			return
		}

		if n > 0 {
			// accumulate message bytes
			buf.Write(b)

			// message terminator?
			if b[0] == 0xFD {
				// a message from the radio?
				r := buf.Bytes()
				if r[2] == 0xE0 {
					break
				}
				buf.Reset()
			}
		} else {
			break
		}
	}

	log.Printf("response %X", buf.Bytes())
}
```
